site_name: kicey's blog
site_url: https://kicey.github.io
plugins:
  - blog:
      blog_dir: blog
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
theme:
  name: material
  logo: ./images/logo.svg
  favicon: ./images/logo.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - index.md
  - Java:
    - '内存布局': java/java 内存结构.md
  - Blog:
    - blog/index.md