site_name: kicey's blog
site_url: https://kicey.github.io
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - blog:
      blog_dir: blog
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
theme:
  name: material
  custom_dir: overrides
  logo: ./images/logo.svg
  favicon: ./images/logo.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.code.copy
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - index.md
  - Java:
    - 内存布局: java/java 内存布局.md
    - Hotspot GC 特性: java/Hotspot GC 特性.md
  - React:
    - Function Style Component: react/4. funcion style component.md
  - Kernel:
    - "使用 buildroot 和 QEMU 调试 linux 内核": kernel/debug_kernel_with_buildroot_qemu.md
  - Redis:
    - "Simple Dynamic String": redis/simple_dynamic_string.md
  - Blog:
    - blog/index.md